### ISSUE TITLE
Preprocess and analyze EEG data stored in the format being specified as Onda?

### ISSUE THREAD

**Issue by likanzhan** [beacon-biosignals/Onda.jl#110]
I'm not sure whether this is an appropriate place to mention this.

Suppose I have read my EEG data as a `Onda` samples data and a `annotation` data.
Is there an easy way to do  some follow-up typical preprocessing and statistical analyses of these data?
such as epoching, re-reference, downsampling etc?

Thanks.

**Comment by jrevels** [comment]
Sorry for the slow response turnaround, just saw this!

> Is there an easy way to do some follow-up typical preprocessing and statistical analyses of these data?
such as epoching, re-reference, downsampling etc?

Onda itself provides a codec/file/storage interface for general LPCM data, but is agnostic to any particular sensor modality (e.g. EEG) and is subsequently agnostic to your choice of analysis tool.

For example, sample data represented as a normal Julia `AbstractArray`, so you would basically use your preferred tooling for manipulating `AbstractArray`s.

At Beacon, we make heavy use of https://github.com/JuliaDSP/DSP.jl, https://github.com/beacon-biosignals/PyMNE.jl and the Tables.jl ecosystem for processing. See the `tour.jl` for some really basic transformations using DataFrames.jl.
