### ISSUE TITLE
enable more granular notion of sensor for `onda.signal`

### ISSUE THREAD

**Issue by jrevels** [beacon-biosignals/Onda.jl#119]
**EDIT: we'll probably go with [this approach](https://github.com/beacon-biosignals/Onda.jl/issues/119#issuecomment-1030687887):**

> - rename `kind::String` to `sensor_label::String`, which will act as a unique signal identifier within a given recording (i.e. we'd require `sensor_label` to be unique across signals in a given recording)
> - add new field `sensor_type::String` which need not be unique within a recording (where the deprecation path is to set it to `sensor_label`)

---

**ORIGINAL CONTENT OF OP:**

Currently:

> Note that this schema allows for the existence of multiple onda.signal instances with the same kind and recording. In this instance, these onda.signal instances should be interpreted as digitized outputs of the same underlying process at their respective spans, thus enabling the representation/storage of discontiguous/overlapping sample data. Beyond this definition, further specification for the resolution of sample data discontinuities and/or overlaps for specific kinds/recordings/etc. is left to downstream, use-case-specific extensions of the onda.signal schema. For example, there may exist an onda.signal with kind="eeg" and span=(start=Nanosecond(0), stop=Nanosecond(1e9)), and another with the same recording/kind but with span=(start=Nanosecond(2e9), stop=Nanosecond(3e9)); downstream consumers may interpret this as a single EEG signal that is sampled for 1 second starting at the beginning of the recording, followed by a 1 second gap, followed by another second of sampling.

Proposal (EDIT: this is original proposal, but I think we'd actually [do this one](https://github.com/beacon-biosignals/Onda.jl/issues/119#issuecomment-1030687887) when we implement this)

- rename `kind` to `sensor_type`
- add new field `sensor_id::Union{Missing,UUID}`
- if `ismissing(sensor_id)`, assume that all other signals with the same `sensor_type` in the recording come from the same sensor with a missing ID

This is borderline non-breaking, gives us better terminology, and enables multiple sensors of the same modality to participate in the same recording

**Comment by jrevels** [comment]
Would be good to figure out how this interacts with: 

> Furthermore, to allow arbitrary cross-signal referencing, a and/or b may be channel names from other signals contained in the recording. If this is the case, such a name must be qualified in the format signal_name.channel_name. For example, an eog signal might have a channel named left-eeg.m1 (the left eye electrode referenced to the mastoid electrode from a 10-20 EEG signal).

Feels like `left-(05827af4-0410-40c9-b294-4eab3f75549e).m1` doesn't have quite the same ring to it as `left-eeg.m1` 😁

**Comment by kleinschmidt** [comment]
This is related to a current issue with importing data formats we see in the wild (e.g., teh MNC dataset from NSRR), where multiple, say, heart rate channels are present in the EDF with different sampling rates/quantization, which correspond to different Samples instances/signals rows.
