### ISSUE TITLE
Use `muladd` / `fma` in encoding/decoding?

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/Onda.jl#146]
E.g. [right now](https://github.com/beacon-biosignals/Onda.jl/blob/dd5d23bd17aab5b07520e40342421829516ef838/src/samples.jl#L386C55-L386C55) we use
```julia
    f = x -> sample_resolution_in_unit * x + sample_offset_in_unit
```
We could use instead `f = x -> fma(sample_resolution_in_unit, x, sample_offset_in_unit)` (or likely better, `muladd`, if we were OK with only using `fma` when available on the hardware, rather than forcing software emulation in that case.)

This would be faster and more accurate, since it avoids the intermediate rounding. Julia will not perform this optimization automatically (at least without `@fastmath` or such) since the compiler isn't allowed to change the results.

**Comment by jrevels** [comment]
Open PR?
