### ISSUE TITLE
The .onda name requirement doesn't play well with S3 buckets

### ISSUE THREAD

**Issue by ararslan** [beacon-biosignals/Onda.jl#26]
If an Onda dataset is stored _as_ an S3 bucket (i.e. not _inside_ an S3 bucket), the name of the bucket can't contain a ., which means that e.g. stuff.onda needs to be stuff-onda or similar. If you mount the S3 bucket as a filesystem with s3fs, you can tell it that the mount point is a directory that ends with .onda, which seems like it would work, but `Dataset("stuff.onda"; create=true)` will fail since the directory exists. (It needs to for s3fs.) Perhaps we should allow `create=true` if the provided directory exists but is empty?

**Comment by jrevels** [comment]
It might be okay to also relax the naming requirement in the spec.

**Comment by hannahilea** [comment]
I am in support of both of these ideas! (I've run into similar issues.)
