### ISSUE TITLE
Add a `SamplesInfo` constructor which accepts `SamplesInfo` + kwargs

### ISSUE THREAD

**Issue by femtomc** [beacon-biosignals/Onda.jl#84]
@ericphanson

Consider one of the current `SamplesInfo` constructors:

```julia
SamplesInfo(; kind, channels, sample_unit,
            sample_resolution_in_unit, sample_offset_in_unit,
            sample_type, sample_rate,
            validate::Bool=Onda.validate_on_construction())
 ```
 this is slightly inconvenient to use if you want to update the `SamplesInfo` on a single field.
 
 I propose including the following:
 ```julia
SamplesInfo(s::SamplesInfo; kind = s.kind, channels = s.channels...)
```
which allows consumers to easily change any of the required fields from an existing `SamplesInfo` instance.

**Comment by ericphanson** [comment]
Onda supports ConstructionBase pretty extensively so you can "modify" stuff with `setproperties`. That way we don't need to add a constructor for each type separately.

**Comment by femtomc** [comment]
Perfect -- thanks!
